# Generated by Django 4.0.10 on 2024-04-20 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaphraseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('input', models.CharField(max_length=26000)),
                ('output', models.JSONField(blank=True, editable=False, null=True)),
                ('model_type', models.CharField(max_length=128)),
                ('text_style', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Paraphrase history',
                'verbose_name_plural': 'Paraphrase histories',
                'db_table': 'paraphrase_history',
            },
        ),
    ]
