# Generated by Django 4.0.10 on 2024-04-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_paraphrasehistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paraphrasehistory',
            name='output',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
